### ISSUE TITLE
Traits or From/To?

### ISSUE THREAD

**Issue by zbraniecki** [zbraniecki/unic-locale#1]
Currently, we have two main structs - `LanguageIdentifier` and `Locale`.

In reality, `Locale` should extend `LanguageIdentifier` with extensions and in the ideal world most APIs that operate on Locales or LanguageIdentifiers should allow for anything that can implement the right methods to be allowed.

So, I'm wondering if we should stick to structs and let people write their From/To so that things like PluralRules or Localization crates just accept anything that can be turned into a `Locale` object.
Or should we turn the two structs into traits and let others implement the traits and everywhere where someone would pass a locale or langid, just expect the right trait.

**Comment by zbraniecki** [comment]
In particular, I have the following use case in mind:

I'm writing `PluralRules` and I need to accept some language identifier. Currently it accepts ` &str` - `pub fn create(lang: &str, prt: PluralRuleType)` but I'd prefer to change it to something more semantically meaningful, and move validation/parsing of the `lang` out of PluralRules. Since no extension keys affect this API, I am happy to just accept `LanguageIdentifier` and no need for the full `Locale`.

I also can imagine someone writing their own struct that contains language identifier information. Should my API accept `Locale`? `LanguageIdentifier` that can be created from `Locale`? Or some trait like` LanguageIdentifierTrait` that `LanguageIdentifier`, `Locale` and anything else can implement?

**Comment by zbraniecki** [comment]
@benham, @manishearth - thoughts?

**Comment by Manishearth** [comment]
I think you can just accept LanguageIdentifier and provide ways to construct that from Locale, etc. Doesn't have to be implicit magic.

**Comment by zbraniecki** [comment]
Ok, added From/Into for Locale<-->LanguageIdentifier.
