### ISSUE TITLE
Mark `get_lang_from_parts` as unsafe

### ISSUE THREAD

**Issue by zbraniecki** [zbraniecki/unic-locale#16]
Quoting Manish:

"Typically you still mark things as unsafe internally up to the point where you can ensure the invariants are upheld

Put another way, every use of `unsafe` could/should have a comment explaining why the invariants are being upheld. If you don't have a way to do that (e.g. here, where the invariants are being upheld elsewhere) you probably need to expand the usage"

_Originally posted by @Manishearth in https://github.com/zbraniecki/unic-locale/pull/15_

**Comment by nox** [comment]
This method shouldn't be unsafe, the `unsafe` keyword is about memory safety and making up wrong lang values is not memory-unsafe.

**Comment by Manishearth** [comment]
It's unsafe because of the use of TinyStr

**Comment by nox** [comment]
Oh I see, I confused myself with `LanguageIdentifier::from_raw_parts_unchecked` which I don't understand why it is unsafe.

**Comment by zbraniecki** [comment]
hmm, yeah, this may be a good candidate to make it safe. Agree @Manishearth ?

**Comment by Manishearth** [comment]
oh, yeah, looking at the code it should be safe
