### ISSUE TITLE
Add example of how to extract unicode extension from Locale

### ISSUE THREAD

**Issue by hjmallon** [zbraniecki/unic-locale#19]
While we have `get_language`, `get_script` etc for Locale I cannot find a good method for getting the information from unicode Extensions.

E.g. maybe something like `loc.extensions.unicode["ca"]` which would return `"buddhist"` if set up as the example in unic-locale. Or maybe `loc.extensions.unicode.get_val("cal")` or `loc.get_unicode_val("cal")`?

If I have missed something then please could I request an example be added to the README to describe how it is done?

**Comment by zbraniecki** [comment]
You didn't miss anything, `unic-locale` is a bit less mature than `unic-langid` - we need to improve the API in `unic-locale` for extensions.

**Comment by zbraniecki** [comment]
One way to handle the unicode ones might be to allow for `loc.extensions.unicode.get("ca")` which would return `Result<Option<&str>>` - the `Result` would be for exists/doesn't exist. The option would be to `does have value` and `&str` would be the optional value.

**Comment by zbraniecki** [comment]
This has been resolved in #30!

**Comment by hjmallon** [comment]
I think the docs I added to the README might be wrong. IIRC they refer to the old Vec interface rather than Iterator.

**Comment by zbraniecki** [comment]
Thank you! Updated the README!
