### ISSUE TITLE
Consider shrinking the likelysubtags list

### ISSUE THREAD

**Issue by zbraniecki** [zbraniecki/unic-locale#42]
Currently `likely_subtags` table is storing the left-side match (say, lang) and on the right side it stores the whole language identifier. But in all cases the right side subtag is exactly the same as the left side.

We could likely just skip the one that is already there. So, for example `LANG_ONLY` could instead of being `(u64, (Option<u64>, Option<u32>, Option<u32>))` (LANG, (LANG, SCRIPT, REGION)) be `(u64, (Option<u32>, Option<u32>))` (LANG, (SCRIPT, REGION)).

**Comment by zbraniecki** [comment]
Actually, there's an exception - where `und-XX` is turned into `ab-XX`. We need to workaround that. Maybe just store an enum - `Some(X), None, Same` where `None` means remove a subtag, `Some` means to add it, and `Same` means to use the input subtag on output?

**Comment by zbraniecki** [comment]
@Manishearth - can you give me your gut feeling on whether the effort is worth it?

Look at https://github.com/zbraniecki/unic-locale/blob/master/unic-langid-impl/src/likelysubtags/tables.rs

Majority of entries have the same first or first/second field with the corresponding field in the last tuple.
Example:

```rust
pub static LANG_ONLY: [(u64, (Option<u64>, Option<u32>, Option<u32>)); 1333] = [
    (24929, (Some(24929), Some(1853120844), Some(21573))),
];
```

here, the `u64` field (lang) matches the first field of the result (also lang).

Another example:

```rust
pub static LANG_SCRIPT: [(u64, u32, (Option<u64>, Option<u32>, Option<u32>)); 28] = [
    (
        24944,
        1650553409,
        (Some(24944), Some(1650553409), Some(19280)),
    ),
];
```

here, the first two fields - lang and script, match the result lang and script.

Since there are cases where this is not true, I can't just skip them, but I can introduce sth like this:

```rust
pub enum SubtagOption<T> {
    Some(T),
    None,
    Same
}

pub static LANG_ONLY: [(u64, (SubtagOption<u64>, SubtagOption<u32>, SubtagOption<u32>)); 1333] = [
    (24929, (SubtagOption::Same, SubtagOption::Some(1853120844), SubtagOption::Some(21573))),
];

pub static LANG_SCRIPT: [(u64, u32, (SubtagOption<u64>, SubtagOption<u32>, SubtagOption<u32>)); 28] = [
    (
        24944,
        1650553409,
        (SubtagOption::Same, SubtagOption::Same, SubtagOption::Some(19280)),
    ),
];
```

This would be a bit of a hassle since we'd have to at runtime shuffle between `Option` returned from `LanguageIdentifier::into_raw_parts` and the `SubtagOption`, but if it saves reasonable amount of space/memory, then it may be a good investment.

What do you think?

**Comment by Manishearth** [comment]
Would it save space? The SubtagOption is going to take up the same space anyway, no?

**Comment by zbraniecki** [comment]
> Would it save space? The SubtagOption is going to take up the same space anyway, no?

`(Some(24944), Some(1650553409), Some(19280)),` vs `(SubtagOption::Same, SubtagOption::Same, SubtagOption::Some(19280)),` - the latter should use less memory, no?

**Comment by Manishearth** [comment]
No, because `::Same` still takes up as much space as the `::Some`, enums take as much space as their largest variant, they have to.

The only difference is that in one case you have Some & None, and in the other you have Some, None, and Same(u32), but those two enums are the same size since Same(u32) takes a full four bytes, and the other two fit in the next one.

**Comment by zbraniecki** [comment]
Ah, that makes sense! Ok, let's close it!
