### ISSUE TITLE
Rename likely subtags methods to minimize/maximize?

### ISSUE THREAD

**Issue by sffc** [zbraniecki/unic-locale#46]
ECMA-402 (TC39-TG2) approved [Intl.Locale](https://github.com/tc39/proposal-intl-locale) for Stage 4 advancement this week.  That proposal uses the names "minimize" and "maximize" instead of "remove_likely_subtags" and "add_likely_subtags".  This thread is spun off from https://github.com/i18n-concept/rust-discuss/issues/3 to discuss whether to adopt the 402 naming scheme.

**Comment by zbraniecki** [comment]
Fixed in https://github.com/zbraniecki/unic-locale/commit/09a163c5ee46ba955bae7a65d8fb1072d941663c
