### ISSUE TITLE
Locale::from_str doesn't seem to work

### ISSUE THREAD

**Issue by sffc** [zbraniecki/unic-locale#48]
I'm probably doing something stupid.  I wrote the following code:

```rust
use unic_locale::Locale;
// ...
let loc = Locale::from_str(input);
```

where `input` is a `&str`.  However, the compiler complains:

> error[E0599]: no function or associated item named `from_str` found for type `unic_locale_impl::Locale` in the current scope

However, the docs say that the FromStr trait is supposedly implemented:

https://docs.rs/unic-locale/0.7.0/unic_locale/struct.Locale.html#impl-FromStr

My Cargo.toml has `unic-locale = "0.7.1"`.

**Comment by zbraniecki** [comment]
If you paste the whole error, there's a useful hint in it:

```
   Compiling unic-locale v0.7.1 (/Users/zbraniecki/projects/unic-locale/unic-locale)
error[E0599]: no function or associated item named `from_str` found for type `unic_locale_impl::Locale` in the current scope
  --> unic-locale/examples/simple-locale.rs:17:23
   |
17 |     let loc = Locale::from_str("pl");
   |                       ^^^^^^^^ function or associated item not found in `unic_locale_impl::Locale`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope, perhaps add a `use` for it:
   |
3  | use std::str::FromStr;
   |

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `unic-locale`.

To learn more, run the command again with --verbose.
```

The `FromStr` trait is not automatically included in your scope.
To solve that, add:

```rust
use std::str::FromStr;
```

But alternatively, `FromStr` autoincludes a different method - `parse` - and the most common way we use is to, instead of including `FromStr`, just do:

```rust
let x: Locale = "pl-u-hc-h12".parse().expect("Parsing failed");
```

**Comment by zbraniecki** [comment]
@sffc - does it answer your question?

**Comment by sffc** [comment]
Yeah, thanks for the tip!  Maybe it's because I haven't written enough Rust code, but at least for me, I find `let x = Type::from_str(s)` to be more readable than `let x: Type = s.parse()`; the factory method pattern feels more familiar to me.
