### ISSUE TITLE
Consider bringing `unic-locale` in line with Rust naming conventions

### ISSUE THREAD

**Issue by filmil** [zbraniecki/unic-locale#52]
For example, [LanguageIdentifier](https://docs.rs/unic-langid/0.7.1/unic_langid/struct.LanguageIdentifier.html) has a getter `language()` and similar, whereas [rust naming conventions](https://doc.rust-lang.org/1.0.0/style/style/naming/README.html#getter/setter-methods-[rfc-344]) would seem to prefer `language()`.

This is a very light suggestion since it's probably a paint to make the change at this point in time; but do consider it.

**Comment by zbraniecki** [comment]
> This is a very light suggestion since it's probably a paint to make the change at this point in time; but do consider it.

This has been fixed in https://github.com/zbraniecki/unic-locale/pull/51 :)

**Comment by filmil** [comment]
Oh, that's cool.  Consider then releasing `0.8.x` perhaps?

**Comment by zbraniecki** [comment]
0.8 released!
