### ISSUE TITLE
Should `LanguageIdentifier::has_variant` have return value of `Result` type?

### ISSUE THREAD

**Issue by filmil** [zbraniecki/unic-locale#55]
Hi @zbraniecki ! 

I am looking around the unic-langid API, specifically: https://docs.rs/unic-langid/0.8.0/unic_langid/struct.LanguageIdentifier.html#method.has_variant

It seems that the `Error`  branch is only because variant could be invalid.  Do you think it could be worth simplifying that API by factoring validation out of the `has` check?  The tradeoff is that we'd then need a `Variant` type (which is always a known-valid variant), but perhaps that is not entirely unreasonable.

I ask because it seems consistent with your recommendation that language ID parsing should be factored out of operations.  This is, of course, in line with the things going on at https://github.com/unicode-org/rust-discuss.

**Comment by zbraniecki** [comment]
I'm not against it. In fact, we could maybe factor out other subtags as well and have `LanguageSubtag`, `ScriptSubtag`, RegionSubtag`, VariantSubtag` that have internal validation?

**Comment by filmil** [comment]
That'd be a worthwhile move in my opinion.  

Once you turn a string-like (`AsRef<[u8]>`) into a say `subtag::Language` (proposing a name), you are certain that it is a valid language.  The APIs can then consume these values without additional error checking so `Result<T, Error>` can become just `T`. 

(The ICU APIs don't do this eager error checking, but I studied those and couldn't see the value in deferring the error checks.)

**Comment by zbraniecki** [comment]
Yeah, I'm a little bit concerned about extending the surface here, but I think it makes sense.
`subtag::Language` sounds good.

One thing I'm not sure about is how to design getters:

```rust
let langid: LanguageIdentifier = "en-US".parse().unwrap();
let lang: subtag::Language = "de".parse().unwrap(); // FromStr
langid.set_language(lang); // infallible
```

that seems clean. Do we *also* allow some fallible setters using `&str`? maybe not. Maybe setters always have to accept correct subtag? That would be very clean, and likely if someone is setting subtags they can validate them before passing to LangId/Locale.

**Comment by filmil** [comment]
One possible alternative that removes the need for `subtag::*` types.  This, apparently, works.
```
let script: LanguageIdentifier = "und-Cyrl".parse().expect("Parsing failed.");
assert_eq!(country.script(), Some("Cyrl"));
```
You get a `LanguageIdentifier`, where most fields are missing, but those that are present are also validated. This could then be used in methods like `LanguageIdentifier::has_variant` to remove the need to parse the variant again. It can simplify the return value just as before, except without introducing more types with very limited utility.  

## Pros

* No need to introduce new types
* Can simplify type signatures on quite a few other methods, which was the main point of the proposal.

## Cons

* Now we can have a `LanguageIdentifier` which is nothing but a script subtag.

  It's possibly a bit confusing to handle an empty language identifier. But, it is validated, and is strictly better to pass around than non-validated `&str`.

**Comment by zbraniecki** [comment]
I think I'm more in favor of `subtags`.
