### ISSUE TITLE
Test with likelysubtags feature errors

### ISSUE THREAD

**Issue by subpop** [zbraniecki/unic-locale#64]
# Description

While packaging `unic-langid-impl` for Fedora, I encountered a build failure. Fedora builds crates individually by downloading the `.crate` from crates.io. The crate for `unic-langid-impl` appears to be missing needed test files.

# Steps to Reproduce

1. Download the crate: `wget -O unic-langid-impl-0.9.0.crate https://crates.io/api/v1/crates/unic-langid-impl/0.9.0/download`
2. Unpack the crate: `tar xf unic-langid-impl-0.9.0.tgz`
3. Run the tests with the `likelysubtags` feature: `cargo test --features likelysubtags`

# Expected Results

The test suit should pass or fail.

# Actual Results

The test suite errors, unable to find test files.

```
error: couldn't read tests/likelysubtags.rs: No such file or directory (os error 2)
```

# Notes

I believe this could be fixed by including `tests/*.rs` in the `include` array in `Cargo.toml`.

**Comment by zbraniecki** [comment]
That seems like a reasonable fix! Would you be able to provide a PR?
