### ISSUE TITLE
Remove proc-macro-hack

### ISSUE THREAD

**Issue by rylev** [zbraniecki/unic-locale#66]
`proc-macro-hack` is only needed if the MSRV is somewhere between 1.31 and 1.45. I don't see the MSRV documented anywhere, but if the MSRV is above 1.45, then it would be good to remove proc-macro-hack. I looked into doing this, and it's pretty straightforward. The only issue is that proc-macro-hack supported `$crate` while regular proc macros don't, so it would be necessary to come up with an alternative strategy.

**Comment by zbraniecki** [comment]
Fixed in https://github.com/zbraniecki/unic-locale/commit/95fb1f46aaa75ad7dea5b3105e5ac9234e3e238d
