### ISSUE TITLE
please include license files in published crates

### ISSUE THREAD

**Issue by decathorpe** [zbraniecki/unic-locale#69]
Both the Apache-2.0 and MIT licenses require that redistributed sources include a copy of the license text. Right now only the git repository contains the license texts themselves, but crates uploaded to and redistributed via crates.io don't.

Adding symbolic links `LICENSE-APACHE -> ../LICENSE-APACHE` (and same for LICENSE-MIT) should make `cargo package` / `cargo publish` pick up these files (assuming they are not excluded by `package.include` / `package.exclude` settings in `Cargo.toml`).

**Comment by zbraniecki** [comment]
Thanks! Fixed in https://github.com/zbraniecki/unic-locale/commit/ab91c95342f5a57c1494697b2c394db95b6d6b61
