### ISSUE TITLE
Add override for skr locale (text direction RTL)

### ISSUE THREAD

**Issue by flodolo** [zbraniecki/unic-locale#70]
Saraiki (skr) is currently not available in CLDR, but it's completely localized in Firefox.

Adding it to CLDR is going to take a long time, so ti would be ideal to have a work-around here (set the direction for the locale, overriding CLDR data).

**Comment by mpQadir** [comment]
This is good idea. It is admitted fact Saraiki is RTL. Otherwise there may be mistake in the sense sentence. In my point of view it should be done.

**Comment by mpQadir** [comment]
I have made a request for adding Saraiki, but Saraiki is not added till. It seems that their is no chance for this in near future. Please look into the matter. It should be done on firefox.
