### ISSUE TITLE
Breaking change from 0.9.1 -> 0.9.2

### ISSUE THREAD

**Issue by aevyrie** [zbraniecki/unic-locale#74]
This error only seems to be present in the `languid!` macro, as far as I can tell. Removing use of this macro avoided the proc macro panic.

```
error: proc macro panicked
 --> src/translation.rs:8:40
  |
8 | const US_ENGLISH: LanguageIdentifier = langid!("en-US");
  |                                        ^^^^^^^^^^^^^^^^
  |
  = help: message: {CRATE_NAME} is present in `Cargo.toml`

error: proc macro panicked
 --> src/translation.rs:9:36
  |
9 | const FRENCH: LanguageIdentifier = langid!("fr");
  |                                    ^^^^^^^^^^^^^
  |
  = help: message: {CRATE_NAME} is present in `Cargo.toml`

error: proc macro panicked
  --> src/translation.rs:10:36
   |
10 | const GERMAN: LanguageIdentifier = langid!("de");
   |                                    ^^^^^^^^^^^^^
   |
   = help: message: {CRATE_NAME} is present in `Cargo.toml`
```

**Comment by aevyrie** [comment]
I'm not able to fix this by simply pinning `unic-langid`, so I'm guessing a transitive dependency is causing this? We ran into this when running cargo update.

Potentially related:
```
      Adding proc-macro-crate v2.0.0
    Removing proc-macro-hack v0.5.20+deprecated
```

**Comment by zbraniecki** [comment]
hmm, sorry for the break! Is your code public? Can I repro?

I'm going to yank the 0.9.2 if this is reproduced and want to fix it for 0.9.3.

**Comment by zbraniecki** [comment]
ok, was able to repro. Yanked. Sorry for that!

**Comment by zbraniecki** [comment]
I think I was able to fix it in https://github.com/zbraniecki/unic-locale/commit/b9b651ae191cff955545172a3a630e9ef8207ca4 . Please, let me know if it will still break.

**Comment by aevyrie** [comment]
No worries, thanks @zbraniecki. The code is not public.
