### ISSUE TITLE
The direction of `pa` and `pa-IN` is reported as RTL, should be LTR

### ISSUE THREAD

**Issue by eemeli** [zbraniecki/unic-locale#76]
This is a regression from the changes in #73 and reported downstream as [Firefox bug 1872962](https://bugzilla.mozilla.org/show_bug.cgi?id=1872962). Previously, Punjabi was correctly detected as LTR, but now it's RTL.

The likely subtags do correctly extend `pa` to `pa-Guru-IN`: https://github.com/zbraniecki/unic-locale/blob/3b8b7a07d4336c88c609916bdb87b49fc8afb415/unic-langid-impl/data/likelySubtags.json#L5027

and the direction of the fully qualified locale is correctly LTR (as is `pa-Guru`).

I think the core issue is that the `pa` locale is incorrectly included in the `LANGS_CHARACTER_DIRECTION_RTL` array. As they're stored as integers, here's what they contain as strings (from hacking a bit at `generate_layout.rs`):
```rust
pub const SCRIPTS_CHARACTER_DIRECTION_LTR: [u32; 16] = [Beng, Cyrl, Deva, Dsrt, Guru, Hans, Hant, Hmnp, Latn, Mtei, Olck, Orya, Shaw, Telu, Tfng, Vaii];
pub const SCRIPTS_CHARACTER_DIRECTION_RTL: [u32; 4] = [Adlm, Arab, Nkoo, Rohg];
pub const SCRIPTS_CHARACTER_DIRECTION_TTB: [u32; 1] = [Mong];
pub const LANGS_CHARACTER_DIRECTION_RTL: [u64; 29] = [apc, ar, az, bal, bgn, bm, ckb, dv, fa, ff, ha, he, ks, lrc, ms, mzn, nqo, pa, ps, rhg, sd, sdh, skr, syr, trw, ug, ur, uz, yi];
```

I think the scripts are all correct, but I've not checked the RTL primary tags.

**Comment by eemeli** [comment]
Some further thoughts: I think the tag needs to be maximized before checking the data. If that's done, then we have:
- `pa-PK` → `pa-Arab-PK`
- `pa-IN` → `pa-Guru-IN`

and then the script being checked before the primary tag will produce the right result.

Otherwise, I think we need to extend the data to cover regions as well.

**Comment by zbraniecki** [comment]
Thanks for reporting! I won't have cycles to work on this anytime very soon. I'm working on migrating Fluent to ICU4X.

If you need a fix soon, you may need to implement a solution yourself. I'm available to brainstorm and review.
